### ISSUE TITLE
Cannot find module 'resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by probonopd** [MD-AZMAL/Sharp-Tune#2]
```
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-7139/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 7139, child pid 7142
```

May be caused by https://github.com/electron-userland/electron-builder/issues/2958

Reference:
https://github.com/AppImage/appimage.github.io/pull/658

**Comment by MD-AZMAL** [comment]
i tracked the issue on https://github.com/electron-userland/electron-builder/issues/2958  and some said 
Build work with v20.14.7 ..... also the configuration works perfectly for nsis installer

**Comment by MD-AZMAL** [comment]
Packaging works fine for deb and AppImage in my ubuntu environment but the AppImage file does'nt run

**Comment by MD-AZMAL** [comment]
maybe downgrading to electron-builder  20.14.7 would solve the problem

**Comment by MD-AZMAL** [comment]
finally the issue is resolved..... closing it
@probonopd i am still curious how you discovered my app 😄

**Comment by probonopd** [comment]
Hi @MD-AZMAL i'm interested in all AppImages out there, so I noticed yours :-)

**Comment by MD-AZMAL** [comment]
cool 😃
